version: '3'
services:
  backend:
    build: ./src/backend
    volumes:
      - ./src/backend:/app
    ports:
      - "5000:5000"
    environment:
      - NAME=World
  frontend:
    build: ./src/frontend
    volumes:
      - ./src/frontend:/app
    ports:
      - "3000:3000"
  script:
    build: ./src/scripts
    volumes:
      - ./src/scripts:/app
